### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by gonzaponte** [jacg/dataflow#1]
There are a bunch of TODOs left from the first version of the code related to the testing suite that shall be addressed in upcoming PRs

- [ ] Test implicit pipes in `fork`
`fork` accepts pipes as arguments, but tuples can be interpreted as pipes and converted implicitly. This feature is not tested.
- [ ] Test `count_filter`
This component is not tested.
- [ ] Test `spy_count`
This component is not tested.
- [ ] (Test polymorphic result of `pipe`)
Not sure this is this still relevant. Are we allowing sinkless pipes?
- [ ] Add test for failure to close sideways in branch
Branches produce two downstreams in the data flow and both must be closed when data stops flowing. A test should ensure this behavior.
- [ ] Test `string_to_pick` and its usage
If the first element in a pipe is a string the data flowing through that pipe is reduced to a specific item. This functionality needs to be tested.
- [ ] Add test for `slice` with `close_all = True`
`slice` takes an optional argument `close_all` to decide whether to stop the full pipeline when it runs out of values. The functionality for `close_all = True` is not tested.

**Comment by jacg** [comment]
Thanks.

Careful: I'm shamelessly and frequently rebasing master at the moment, exploring different organizations and toolsets. Probably unlikely to touch the actual Python source files during this process.

**Comment by jacg** [comment]
Concerning `string_to_pick`: at the moment this must be a single string. It might be useful to allow a tuple of strings here, too. I'd also like to think about what could be done with named tuples, in this space.

If we expand the functionality of `string_to_pick` it should be renamed to something like `items_to_pick`.
